name: Composer install

description: Install composer dependencies

inputs:
  php-coverage:
    default: 'none'
    description: Coverage driver to use.
    required: false

  php-extensions:
    default: ''
    description: PHP extensions to install.
    required: false

  php-tools:
    default: 'cs2pr'
    description: PHP tools to install.
    required: false

  php-version:
    default: '8.5'
    description: The PHP version to use.
    required: false

  pie-extensions:
    default: ''
    description: Comma-separated PIE extension packages to install.
    required: false

runs:
  using: composite

  steps:
    - name: Setup PHP
      uses: hosmelq/.github/.github/actions/php-setup@main
      with:
        php-coverage: ${{ inputs.php-coverage }}
        php-extensions: ${{ inputs.php-extensions }}
        php-tools: ${{ inputs.php-tools }}
        php-version: ${{ inputs.php-version }}
        pie-extensions: ${{ inputs.pie-extensions }}

    - name: Get composer cache directory
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Restore composer cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache.outputs.dir }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install composer dependencies
      run: composer install --no-interaction --no-progress --prefer-dist
      shell: bash
