name: pnpm install

description: Install pnpm dependencies

inputs:
  fontawesome-npm-auth-token:
    description: The Font Awesome NPM auth token.
    required: false

  node-version:
    default: '22'
    description: The Node.js version to use.
    required: false

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: pnpm install
      shell: bash
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ inputs.fontawesome-npm-auth-token }}
