name: Run Danger JS

description: Run Danger JS for automated PR review

inputs:
  danger-args:
    default: ''
    description: Additional arguments to pass to Danger JS.
    required: false

  dangerfile:
    default: 'dangerfile.js'
    description: Path to the dangerfile.
    required: false

  node-version:
    default: '24'
    description: The Node.js version to use.
    required: false

  working-directory:
    default: '.'
    description: Directory to run package manager commands in.
    required: false

runs:
  using: composite

  steps:
    - name: Install dependencies
      uses: hosmelq/.github/.github/actions/npm-install@main
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.working-directory }}

    - name: Run Danger JS
      env:
        DANGER_ARGS: ${{ inputs.danger-args }}
        DANGERFILE: ${{ inputs.dangerfile }}
        GITHUB_TOKEN: ${{ github.token }}
      run: nubx danger ci --dangerfile "$DANGERFILE" $DANGER_ARGS
      shell: bash
      working-directory: ${{ inputs.working-directory }}
