name: Run Danger JS

description: Run Danger JS for automated PR review

inputs:
  danger-args:
    default: ''
    description: Additional arguments to pass to Danger JS.
    required: false

  dangerfile:
    default: 'dangerfile.js'
    description: Path to the dangerfile.
    required: false

  node-version:
    default: '22'
    description: The Node.js version to use.
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm dependencies
      uses: hosmelq/.github/.github/actions/pnpm-install@main
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run Danger JS
      shell: bash
      run: pnpm danger ci --dangerfile ${{ inputs.dangerfile }} ${{ inputs.danger-args }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
