name: Run Danger JS

description: Run Danger JS for automated PR review

inputs:
  danger-args:
    default: ''
    description: Additional arguments to pass to Danger JS.
    required: false

  dangerfile:
    default: 'dangerfile.js'
    description: Path to the dangerfile.
    required: false

  node-version:
    default: '22'
    description: The Node.js version to use.
    required: false

  package-manager:
    default: 'bun'
    description: Package manager to use (bun or pnpm).
    required: false

  working-directory:
    default: '.'
    description: Directory to run package manager commands in.
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install dependencies
      uses: hosmelq/.github/.github/actions/npm-install@main
      with:
        node-version: ${{ inputs.node-version }}
        package-manager: ${{ inputs.package-manager }}
        working-directory: ${{ inputs.working-directory }}

    - name: Run Danger JS
      run: |
        if [ "${{ inputs.package-manager }}" = "bun" ]; then
          bunx danger ci --dangerfile "${{ inputs.dangerfile }}" ${{ inputs.danger-args }}
        else
          pnpm run danger ci --dangerfile "${{ inputs.dangerfile }}" ${{ inputs.danger-args }}
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
