name: Check Rector

description: Run Rector code quality checks

inputs:
  php-coverage:
    default: 'none'
    description: Coverage driver to use.
    required: false

  php-extensions:
    default: ''
    description: PHP extensions to install.
    required: false

  php-tools:
    default: 'cs2pr'
    description: PHP tools to install.
    required: false

  php-version:
    default: '8.4'
    description: The PHP version to use.
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install composer dependencies
      uses: hosmelq/.github/.github/actions/composer-install@main
      with:
        php-coverage: ${{ inputs.php-coverage }}
        php-extensions: ${{ inputs.php-extensions }}
        php-tools: ${{ inputs.php-tools }}
        php-version: ${{ inputs.php-version }}

    - name: Run Rector
      shell: bash
      run: vendor/bin/rector --ansi --dry-run
