name: Autofix PHP

description: Automatically fix PHP code style using Pint

inputs:
  php-coverage:
    default: 'none'
    description: Coverage driver to use.
    required: false

  php-extensions:
    default: ''
    description: PHP extensions to install.
    required: false

  php-tools:
    default: 'cs2pr'
    description: PHP tools to install.
    required: false

  php-version:
    default: '8.5'
    description: The PHP version to use.
    required: false

  pie-extensions:
    default: ''
    description: Comma-separated PIE extension packages to install.
    required: false

runs:
  using: composite

  steps:
    - name: Install composer dependencies
      uses: hosmelq/.github/.github/actions/composer-install@main
      with:
        php-coverage: ${{ inputs.php-coverage }}
        php-extensions: ${{ inputs.php-extensions }}
        php-tools: ${{ inputs.php-tools }}
        php-version: ${{ inputs.php-version }}
        pie-extensions: ${{ inputs.pie-extensions }}

    - name: Run Pint
      run: composer pint
      shell: bash

    - name: Autofix
      uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1
