name: Build frontend

description: Build the frontend application

inputs:
  fontawesome-npm-auth-token:
    description: The Font Awesome NPM auth token.
    required: false

  node-version:
    default: '22'
    description: The Node.js version to use.
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm dependencies
      uses: hosmelq/.github/.github/actions/pnpm-install@main
      with:
        fontawesome-npm-auth-token: ${{ inputs.fontawesome-npm-auth-token }}
        node-version: ${{ inputs.node-version }}

    - name: Build frontend
      shell: bash
      run: pnpm build
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ inputs.fontawesome-npm-auth-token }}
