name: Check PHPStan

description: Run PHPStan static analysis

inputs:
  php-coverage:
    description: Coverage driver to use.
    required: false
    default: 'none'
  
  php-extensions:
    description: PHP extensions to install.
    required: false
    default: ''
  
  php-tools:
    description: PHP tools to install.
    required: false
    default: 'cs2pr'
  
  php-version:
    description: The PHP version to use.
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install composer dependencies
      uses: hosmelq/.github/.github/actions/composer-install@main
      with:
        php-coverage: ${{ inputs.php-coverage }}
        php-extensions: ${{ inputs.php-extensions }}
        php-tools: ${{ inputs.php-tools }}
        php-version: ${{ inputs.php-version }}

    - name: Run PHPStan
      shell: bash
      run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
