name: Continuous integration (JS)

on:
  workflow_call:
    inputs:
      node-version:
        description: The Node.js version to use.
        required: true
        type: string
    
    secrets:
      fontawesome-npm-auth-token:
        description: The Font Awesome NPM auth token.
        required: false

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  check-code-style:
    name: Check code style

    runs-on: ubuntu-latest

    steps:
      - name: Check JavaScript lint
        uses: hosmelq/.github/.github/actions/js-lint-check@main
        with:
          node-version: ${{ inputs.node-version }}
          fontawesome-npm-auth-token: ${{ secrets.fontawesome-npm-auth-token }}

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Build frontend
        uses: hosmelq/.github/.github/actions/js-frontend-build@main
        with:
          node-version: ${{ inputs.node-version }}
          fontawesome-npm-auth-token: ${{ secrets.fontawesome-npm-auth-token }}
